export default {
  login: "Login",
  mobileNumber: "Mobile Number",
  password: "Password",
  signIn: "Sign In",
  signUp: "Don’t have an account? Sign Up",
  selectLanguage: "Select Language",
  english: "English",
  hindi: "हिन्दी",
  OFFERS: "OFFERS",
  CATEGORIES: "CATEGORIES",
  PRODUCTS: "PRODUCTS",
  ADD_PRODUCT: "ADD PRODUCT",
  EDIT_PRODUCT: "EDIT PRODUCT",
  MEMBER: "MEMBER",
  LANGUAGE: "LANGUAGE",
  ORDER_HISTORY: "ORDER HISTORY",
  PRODUCTS_DETAIL: "Product Details",
  CART: "Cart",
  LOGOUT: "LOGOUT",
  nepali: "नेपाली",
  SELECT_COLOR: "Select Color",
  SELECT_SIZE: "Select Size",
  SIZE: "Size",
  REVIEW_ORDER: "Review Order", 
  ADDRESS: "Address",
  ADD_ADDRESS: "Add Address",
  EDIT_ADDRESS: "Edit Address",
  ADD_TO_CART: "Add to cart",
  GO_TO_CART: "Go to cart",
  PLACE_ORDER: "Place Order",
  TOTAL: "Total",
  CONFIRM_ORDER: "Confirm Order",
  PRODUCT_COLOR:"Colors",
  YOU_MAY_ALSO_LIKE: "You may also like",
  PRODUCTS_DECRIPTION: "Product Description",
  errorMobilePassword: "Please enter mobile number and password",
  errorMobile: "Please enter valid 10 digit mobile number",
  YOU_SAVED: "You saved",
  BILLING_SUMMARY: "Billing Summary",
  TOTAL_ORIGINAL_PRICE: "Total Original Price",
  TOTAL_DISCOUNT: "Total Discount",
  GST_AMOUNT: "GST Amount",
  NET_PAYABLE: "Net Payable",
  WISHLIST: "Wishlist",
  BUS_SERVICE: "Bus Service",
  BOOKING_FOR_BUS: "Booking for {{bus}}",
  TICKET_BOOKING_STATUS: "Your Ticket Booking",
  AGE: "Age",
  GENDER: "Gender",
  BUS_NO: "Bus No",
  OPERATOR: "Bus Name",
  TOTAL: "Total",
  PASSENGERS: "Passengers",
  OPERATOR_PHONE: "Contact Us",
  RECHARGE: "Recharge",
  RECHARGE_NOW: "Recharge Now",
  ENTER_MOBILE_KHALTI: "Enter Mobile No./ Khalti ID",
  ENTER_MOBILE: "Enter Mobile No.",
  ENTER_AMOUNT: "Enter Amount (20 - 25000)",
  SELECT_PACK: "Select Recharge Pack",
  MOBILE_RECHARGE_AND_TOP_UP: "Mobile Recharge And Top-up",
  SELECT_GENDER: "Select Gender",
  NAME: "Name",
  PHONE_NUMBER: "Phone Number",
  ADD_PASSENGER: "Add Passenger",
  BOOK_NOW: "Book Now",
  SOURCE: "Source",
  DESTINATION: "Destination",
  DATE: "Date",
  SELECT_SOURCE: "Select Source",
  SELECT_DESTINATION: "Select Destination",
  SELECT_DATE: "Select Date",
  SEARCH_BUSES: "Search Buses",
  NO_BUSES_FOUND: "No buses found",
  PLEASE_SELECT_SOURCE_AND_DESTINATION: "Please select source and destination",
  SOURCE_AND_DESTINATION_CANNOT_BE_SAME: "Source and destination cannot be same",
  ERROR: "Error",
  SOMETHING_WENT_WRONG: "Something went wrong",
  TERMS_AND_CONDITIONS: "Terms & Conditions",
  I_AGREE_TO_TERMS: "I agree to the ",
  NO_BOOKINGS: "No bookings found",
  RECHARGE_STATUS: "Recharge Status",
  RECHARGE_HISTORY: "Recharge History",
  STATUS: "Status",
  EDIT_PROFILE: "Edit Profile",
  WALLET_DETAILS: "Wallet Details"
};