export default {
  login: "Login",
  mobileNumber: "Mobile Number",
  password: "Password",
  signIn: "Sign In",
  signUp: "Don’t have an account? Sign Up",
  selectLanguage: "Select Language",
  english: "English",
  hindi: "हिन्दी",
  OFFERS: "OFFERS",
  CATEGORIES: "Our Products and Services",
  PRODUCTS: "PRODUCTS",
  ADD_PRODUCT: "ADD PRODUCT",
  EDIT_PRODUCT: "EDIT PRODUCT",
  MEMBER: "MEMBER",
  LANGUAGE: "LANGUAGE",
  ORDER_HISTORY: "ORDER HISTORY",
  PRODUCTS_DETAIL: "Product Details",
  CART: "Cart",
  LOGOUT: "LOGOUT",
  nepali: "नेपाली",
  SELECT_COLOR: "Select Color",
  SELECT_SIZE: "Select Size",
  SIZE: "Size",
  REVIEW_ORDER: "Review Order", 
  ADDRESS: "Address",
  ADD_ADDRESS: "Add Address",
  EDIT_ADDRESS: "Edit Address",
  ADD_TO_CART: "Add to cart",
  GO_TO_CART: "Go to cart",
  PLACE_ORDER: "Place Order",
  CONTINUE: "Continue",
  PROCEED_TO_PAYMENT: "Proceed to Payment",
  PAYMENT: "Payment",
  TOTAL: "Total",
  CONFIRM_ORDER: "Confirm Order",
  PRODUCT_COLOR:"Colors",
  YOU_MAY_ALSO_LIKE: "You may also like",
  PRODUCTS_DECRIPTION: "Product Description",
  errorMobilePassword: "Please enter mobile number and password",
  errorMobile: "Please enter valid 10 digit mobile number",
  YOU_SAVED: "You saved",
  BILLING_SUMMARY: "Billing Summary",
  TOTAL_ORIGINAL_PRICE: "Total Original Price",
  TOTAL_DISCOUNT: "Total Discount",
  GST_AMOUNT: "GST Amount",
  NET_PAYABLE: "Net Payable",
  WISHLIST: "Wishlist",
  BUS_SERVICE: "Bus Service",
  BOOKING_FOR_BUS: "Booking for {{bus}}",
  TICKET_BOOKING_STATUS: "Your Ticket Booking",
  AGE: "Age",
  GENDER: "Gender",
  BUS_NO: "Bus No",
  OPERATOR: "Bus Name",
  TOTAL: "Total",
  PASSENGERS: "Passengers",
  OPERATOR_PHONE: "Contact Us",
  RECHARGE: "Recharge",
  RECHARGE_NOW: "Recharge Now",
  ENTER_MOBILE_KHALTI: "Enter Mobile No./ Khalti ID",
  ENTER_MOBILE: "Enter Mobile No.",
  ENTER_AMOUNT: "Enter Amount (20 - 25000)",
  SELECT_PACK: "Select Recharge Pack",
  MOBILE_RECHARGE_AND_TOP_UP: "Mobile Recharge And Top-up",
  SELECT_GENDER: "Select Gender",
  NAME: "Name",
  PHONE_NUMBER: "Phone Number",
  ADD_PASSENGER: "Add Passenger",
  BOOK_NOW: "Book Now",
  SOURCE: "Source",
  DESTINATION: "Destination",
  DATE: "Date",
  SELECT_SOURCE: "Select Source",
  SELECT_DESTINATION: "Select Destination",
  SELECT_DATE: "Select Date",
  SEARCH_BUSES: "Search Buses",
  NO_BUSES_FOUND: "No buses found",
  PLEASE_SELECT_SOURCE_AND_DESTINATION: "Please select source and destination",
  SOURCE_AND_DESTINATION_CANNOT_BE_SAME: "Source and destination cannot be same",
  ERROR: "Error",
  SOMETHING_WENT_WRONG: "Something went wrong",
  TERMS_AND_CONDITIONS: "Terms & Conditions",
  I_AGREE_TO_TERMS: "I agree to the ",
  NO_BOOKINGS: "No bookings found",
  RECHARGE_STATUS: "Recharge Status",
  RECHARGE_HISTORY: "Recharge History",
  STATUS: "Status",
  EDIT_PROFILE: "Edit Profile",
  WALLET_DETAILS: "Wallet Details",
  MY_ORDERS: "My Orders",
  ORDER_DETAILS: "Order Details",
  ELECTRICITY_BILL: "Electricity Bill",
  BILLS_AND_RECHARGE: "Bills & Recharge",
  TELANGANA_NEPALI_SABHA: "Telangana Nepali Sabha",
  Either_in_ID_1_or_ID_2_Age_should_be_mentioned: "The age must be mentioned in either ID-1 or ID-2.", 
  UPLOAD_ID_1_PROOF: "Upload ID-1 Proof",
  UPLOAD_ID_2_PROOF: "Upload ID-2 Proof", 
  CONTACT_NUMBER: "Contact Number",
  NEPAL_CONTACT_NUMBER: "Nepal Contact Number",
  NEPAL_ADDRESS: "Nepal Address",
  INDIA_ADDRESS: "India Address",
  NEPAL_PROOF_IMAGE: "Nepal Proof Image",
  INDIA_PROOF_IMAGE: "India Proof Image",
  SUBMIT_APPLICATION: "Submit Application",
  UPLOAD_NEPAL_ADDRESS_PROOF: "Upload Nepal Address Proof",
  UPLOAD_INDIA_PROOF: "Upload India Address Proof",
  GENDER_MALE: "Male",
  GENDER_FEMALE: "Female",
  GENDER_OTHER: "Other",
  DOB: "Date of Birth",
  NEPAL_CONTACT_NUMBER_LABEL: "Contact Number of Nepal",
  ENTER_CONTACT_NUMBER: "Enter Contact Number",
  ENTER_NEPAL_CONTACT_NUMBER: "Enter Contact Number of Nepal",
  ENTER_NEPAL_ADDRESS: "Enter Nepal Address",
  ENTER_INDIA_ADDRESS: "Enter India Address",
  INDIA_CONTACT_NUMBER_LABEL: "Contact Number of India",
  ENTER_CONTACT_NUMBER_OF_INDIA: "Enter Contact Number of India",
  ID_1_NAME: "ID-1 Name",
  ID_2_NAME: "ID-2 Name",
  ID_1_OF_NEPAL: "ID-1 of Nepal",
  ID_2_OF_NEPAL: "ID-2 of Nepal",
  ENTER_NAME_FOR_ID_1: "Enter Name for ID-1 of Nepal",
  ENTER_NAME_FOR_ID_2: "Enter Name for ID-2 of Nepal",
  ENTER_NEPAL_ID_1: "Enter ID-1 of Nepal",
  ENTER_NEPAL_ID_2: "Enter ID-2 of Nepal",
  ENTER_NEPAL_ADDRESS: "Enter Nepal Address",
  ENTER_INDIA_ADDRESS: "Enter India Address",
  DOB_PLACEHOLDER: "DD/MM/YYYY",
  SUBMIT_APPLICATION: "Submit Application",
  ENTER_ID_1_OF_NEPAL: "Enter ID-1 of Nepal",
  ENTER_ID_2_OF_NEPAL: "Enter ID-2 of Nepal",
  ENTER_INDIA_CONTACT_NUMBER: "Enter Contact Number of India",
  INFO: "Info",
  PRAWASI_CARD_APPLICATION: "Prawasi Card Application",
  MY_APPLICATIONS: "Prawasi Card Applications",
  CONTACT_US: "Contact Us",
  OUT_OF_STOCK: "Out of Stock",
  ATTENTION: "Attention",
  TICKET_BOOKING_NETWORK_ERROR: "Ticket Booking Network Error",
  TICKET_BOOKING_NETWORK_ERROR_DETAIL: "If your payment was successful, your booking may still be processing due to a temporary network issue.\n\nPlease check your Booking History in a few moments. If your booking is still not visible, please contact our support team with your payment details.",
  DELIVERY_CHARGES: "Delivery Charges",
  PRODUCT_ADDED_TO_CART: "Product added to cart successfully",
  CONTINUE_SHOPPING: "Continue Shopping",
  GO_TO_CART: "Go to Cart",
  SUCCESS: "Success",
  ERROR: "Error",
  OK: "OK",
  SUCCESSFULLY_ADDED: "Successfully added",
  DELETE_ITEM: "Delete Item",
  DELETE_ITEM_CONFIRMATION: "Are you sure you want to delete this item?",
  YES: "Yes",
  NO: "No",
  CANCEL: "Cancel",
  PLACE_ORDER: "Place Order",
  PROCEED_TO_PAY: "Proceed to Pay",
  PAY_NOW: "Pay Now",
  INTERNET_PROVIDERS: "Internet Providers",
  MORE_IN: "More in",
};