export default {
  login: "Login",
  mobileNumber: "Mobile Number",
  password: "Password",
  signIn: "Sign In",
  signUp: "Don’t have an account? Sign Up",
  selectLanguage: "Select Language",
  english: "English",
  hindi: "हिन्दी",
  OFFERS: "OFFERS",
  CATEGORIES: "CATEGORIES",
  PRODUCTS: "PRODUCTS",
  ADD_PRODUCT: "ADD PRODUCT",
  EDIT_PRODUCT: "EDIT PRODUCT",
  MEMBER: "MEMBER",
  LANGUAGE: "LANGUAGE",
  ORDER_HISTORY: "ORDER HISTORY",
  PRODUCTS_DETAIL: "Product Details",
  LOGOUT: "LOGOUT",
  nepali: "नेपाली",
  SELECT_COLOR: "Select Color",
  SELECT_SIZE: "Select Size",
  PRODUCTS_DECRIPTION: "Product Description",
  errorMobilePassword: "Please enter mobile number and password",
  errorMobile: "Please enter valid 10 digit mobile number",
};