export default {
  login: "लॉगिन",
  mobileNumber: "मोबाइल नंबर",
  password: "पासवर्ड",
  signIn: "साइन इन",
  signUp: "खाता नहीं है? साइन अप करें",
  selectLanguage: "भाषा चुनें",
  english: "English",
  hindi: "हिंदी",
  OFFERS: "ऑफ़र",
  CATEGORIES: "श्रेणियाँ",
  MEMBER: "सदस्य",
  LANGUAGE: "भाषा",
  PRODUCTS: "उत्पाद",
  ORDER_HISTORY: "ऑर्डर इतिहास",
  LOGOUT: "लॉगआउट",
  nepali: "नेपाली",
  PRODUCTS_DETAIL: "उत्पाद विवरण",
  CART: "कार्ट",
  SELECT_COLOR: "रंग चुनें",
  SELECT_SIZE: "नाप चुनें",
  PLACE_ORDER: "ऑर्डर बुक करें",
  ADD_TO_CART:"कार्ट में जोड़ें",
  GO_TO_CART: "कार्ट पर जाएं",
  REVIEW_ORDER: "ऑर्डर की समीक्षा करें",
  ADDRESS: "पता",
  ADD_ADDRESS: "पता जोड़ें",
  EDIT_ADDRESS: "पते में बदलाव करें",
  TOTAL: "कुल",
  CONFIRM_ORDER: "कृपया आदेश की पुष्टि करें",
  PRODUCT_COLOR:"रंग",
  YOU_MAY_ALSO_LIKE: "आपको यह भी पसंद आ सकता हैं",
  SIZE: "नाप",
  PRODUCTS_DECRIPTION: "उत्पाद विवरण",
  errorMobilePassword: "कृपया मोबाइल नंबर और पासवर्ड दर्ज करें",
  errorMobile: "कृपया सही 10 अंकों का मोबाइल नंबर दर्ज करें",
  YOU_SAVED: "आपने बचाया",
  BILLING_SUMMARY: "बिलिंग सारांश",
  TOTAL_ORIGINAL_PRICE: "कुल मूल कीमत",
  TOTAL_DISCOUNT: "कुल छूट",
  GST_AMOUNT: "GST राशि",
  NET_PAYABLE: "शुद्ध देय",
  WISHLIST: "इच्छा सूची",
  BUS_SERVICE: "बस सेवा",
  BOOKING_FOR_BUS: "{{bus}} के लिए बुकिंग",
  TICKET_BOOKING_STATUS: "आपकी टिकट बुकिंग",
  AGE: "आयु",
  GENDER: "लिंग",
  BUS_NO: "बस नंबर",
  OPERATOR: "बस का नाम",
  TOTAL: "कुल",
  PASSENGERS: "यात्री",
  OPERATOR_PHONE: "संपर्क करें",
  RECHARGE: "रिचार्ज",
  RECHARGE_NOW: "अभी रिचार्ज करें",
  ENTER_MOBILE_KHALTI: "मोबाइल नंबर / खल्ती आईडी दर्ज करें",
  ENTER_MOBILE: "मोबाइल नंबर दर्ज करें",
  ENTER_AMOUNT: "राशि दर्ज करें (20 - 25000)",
  MOBILE_RECHARGE_AND_TOP_UP: "मोबाइल रिचार्ज और टॉप अप",
  SELECT_PACK: "रिचार्ज पैक चुनें",
  ADD_PASSENGER: "यात्री जोड़ें",
  BOOK_NOW: "अभी बुक करें",
  SOURCE: "स्रोत",
  DESTINATION: "गंतव्य",
  DATE: "तारीख",
  SELECT_SOURCE: "स्रोत चुनें",
  SELECT_DESTINATION: "गंतव्य चुनें",
  SELECT_DATE: "तारीख चुनें",
  SEARCH_BUSES: "बस खोजें",
  NO_BUSES_FOUND: "कोई बस नहीं मिली",
  PLEASE_SELECT_SOURCE_AND_DESTINATION: "कृपया स्रोत और गंतव्य चुनें",
  SOURCE_AND_DESTINATION_CANNOT_BE_SAME: "स्रोत और गंतव्य समान नहीं हो सकते",
  ERROR: "त्रुटि",
  SOMETHING_WENT_WRONG: "कुछ गलत हो गया",
  TERMS_AND_CONDITIONS: "नियम और शर्तें",
  I_AGREE_TO_TERMS: "मैं नियमों से सहमत हूं",
  PHONE_NUMBER: "फोन नंबर",
  NAME: "नाम",
  SELECT_GENDER: "लिंग चुनें",
  NO_BOOKINGS: "कोई बुकिंग नहीं मिली",
  RECHARGE_HISTORY: "रिचार्ज इतिहास",
  RECHARGE_STATUS: "रिचार्ज स्थिति",
  STATUS: "स्थिति",
  EDIT_PROFILE: "प्रोफ़ाइल संपादित करें",
  WALLET_DETAILS: "वॉलेट का विवरण"
};