export default {
  login: "लगइन",
  mobileNumber: "मोबाइल नम्बर",
  password: "पासवर्ड",
  signIn: "साइन इन",
  signUp: "खाता छैन? साइन अप गर्नुहोस्",
  selectLanguage: "भाषा छान्नुहोस्",
  english: "English",
  OFFERS: "अफरहरू",
  CATEGORIES: "श्रेणिहरू",
  PRODUCTS: "उत्पादहरू",
  MEMBER: "सदस्य",
  LANGUAGE: "भाषा",
  ORDER_HISTORY: "अर्डर इतिहास",
  LOGOUT: "लगआउट",
  hindi: "हिन्दी",
  nepali: "नेपाली",
  PRODUCTS_DETAIL: "उत्पाद विवरण",
  CART: "कार्ट",
  SIZE: "नाप",
  SELECT_COLOR: "रंग छान्नुहोस्",
  SELECT_SIZE: "नाप छान्नुहोस्",
  PLACE_ORDER: "अर्डर बुक गर्नुहोस्",
  ADD_TO_CART:"कार्टमा हाल्नुहोस्",
  GO_TO_CART: "कार्टमा जानुहोस्",
  REVIEW_ORDER: "अर्डरको समीक्षा गर्नुहोस्",
  ADDRESS: "ठेगाना",
  ADD_ADDRESS: "ठेगाना थप्नुहोस्",
  EDIT_ADDRESS: "ठेगाना परिवर्तन गर्नुहोस्",
  TOTAL: "कूल",
  CONFIRM_ORDER: "अर्डर पुष्टि गर्नुहोस्",
  PRODUCT_COLOR:"रंग",
  YOU_MAY_ALSO_LIKE: "तपाईं पनि मन सक्छ",
  PRODUCTS_DECRIPTION: "उत्पाद विवरण",
  errorMobilePassword: "कृपया मोबाइल नम्बर र पासवर्ड प्रविष्ट गर्नुहोस्",
  errorMobile: "कृपया मान्य 10 अंकोंको मोबाइल नम्बर प्रविष्ट गर्नुहोस्",
  YOU_SAVED: "तपाईंले बचाए",
  BILLING_SUMMARY: "बिलिंग सारांश",
  TOTAL_ORIGINAL_PRICE: "कुल मूल कीमत",
  TOTAL_DISCOUNT: "कुल छूट",
  GST_AMOUNT: "GST राशि",
  NET_PAYABLE: "शुद्ध देय",
  WISHLIST: "इच्छा सूची",
  BUS_SERVICE: "बस सेवा",
  BOOKING_FOR_BUS: "{{bus}} को लागि बुकिङ",
  TICKET_BOOKING_STATUS: "तपाईंको टिकट बुकिंग",
  AGE: "उम्र",
  GENDER: "लिङ्ग",
  BUS_NO: "बस नम्बर",
  OPERATOR: "बस को नाम",
  TOTAL: "कुल",
  PASSENGERS: "यात्रुहरू",
  OPERATOR_PHONE: "हामीलाई सम्पर्क गर्नुहोस",
  RECHARGE: "रिचार्ज",
  RECHARGE_NOW: "अहिले रिचार्ज गर्नुहोस्",
  ENTER_MOBILE_KHALTI: "मोबाइल नम्बर / खल्ती आईडी प्रविष्ट गर्नुहोस्",
  ENTER_AMOUNT: "राशि प्रविष्ट गर्नुहोस् (20 - 25000)",
  MOBILE_RECHARGE_AND_TOP_UP: "मोबाइल रिचार्ज र टप अप",
  ENTER_MOBILE: "मोबाइल नम्बर प्रविष्ट गर्नुहोस्",
  SELECT_PACK: "रिचार्ज प्याक छान्नुहोस्",
  ADD_PASSENGER: "यात्रु थप्नुहोस्",
  BOOK_NOW: "बुक गर्नुहोस्",
  SOURCE: "स्रोत",
  DESTINATION: "गंतव्य",
  DATE: "तारीख",
  SELECT_SOURCE: "स्रोत चयन गर्नुहोस्",
  SELECT_DESTINATION: "गंतव्य चयन गर्नुहोस्",
  SELECT_DATE: "तारीख चयन गर्नुहोस्",
  SEARCH_BUSES: "बस खोज्नुहोस्",
  NO_BUSES_FOUND: "कुनै बस भेटिएन",
  PLEASE_SELECT_SOURCE_AND_DESTINATION: "कृपया स्रोत र गंतव्य चयन गर्नुहोस्",
  SOURCE_AND_DESTINATION_CANNOT_BE_SAME: "स्रोत र गंतव्य समान हुन सक्दैन",
  ERROR: "त्रुटि",
  SOMETHING_WENT_WRONG: "कुछ गलत हो गयो",
  TERMS_AND_CONDITIONS: "नियम र शर्तें",
  I_AGREE_TO_TERMS: "म नियमहरूसँग सहमत छु।",
  PHONE_NUMBER: "फोन नम्बर",
  NAME: "नाम",
  SELECT_GENDER: "लिङ्ग चयन गर्नुहोस्",
  NO_BOOKINGS: "कुनै बुकिङ भेटिएन",
  RECHARGE_HISTORY: "रिचार्ज इतिहास",
  RECHARGE_STATUS: "रिचार्ज स्थिति",
  STATUS: "स्थिति",
  EDIT_PROFILE: "प्रोफ़ाइल संपादित करें",
};