export default {
  login: "लगइन",
  mobileNumber: "मोबाइल नम्बर",
  password: "पासवर्ड",
  signIn: "साइन इन",
  signUp: "खाता छैन? साइन अप गर्नुहोस्",
  selectLanguage: "भाषा छान्नुहोस्",
  english: "English",
  OFFERS: "अफरहरू",
  CATEGORIES: "श्रेणिहरू",
  PRODUCTS: "उत्पादहरू",
  MEMBER: "सदस्य",
  LANGUAGE: "भाषा",
  ORDER_HISTORY: "अर्डर इतिहास",
  LOGOUT: "लगआउट",
  hindi: "हिन्दी",
  nepali: "नेपाली",
  PRODUCTS_DETAIL: "उत्पाद विवरण",
  SELECT_COLOR: "रंग छान्नुहोस्",
  SELECT_SIZE: "आकार छान्नुहोस्",
  PRODUCTS_DECRIPTION: "उत्पाद विवरण",
  errorMobilePassword: "कृपया मोबाइल नम्बर र पासवर्ड प्रविष्ट गर्नुहोस्",
  errorMobile: "कृपया मान्य 10 अंकोंको मोबाइल नम्बर प्रविष्ट गर्नुहोस्",
};