export default {
  login: "लगइन",
  mobileNumber: "मोबाइल नम्बर",
  password: "पासवर्ड",
  signIn: "साइन इन",
  signUp: "खाता छैन? साइन अप गर्नुहोस्",
  selectLanguage: "भाषा छान्नुहोस्",
  english: "English",
  OFFERS: "अफरहरू",
  CATEGORIES: "हाम्रो उत्पादन र सेवाहरू",
  PRODUCTS: "उत्पादहरू",
  MEMBER: "सदस्य",
  LANGUAGE: "भाषा",
  ORDER_HISTORY: "अर्डर इतिहास",
  LOGOUT: "लगआउट",
  hindi: "हिन्दी",
  nepali: "नेपाली",
  PRODUCTS_DETAIL: "उत्पाद विवरण",
  CART: "कार्ट",
  SIZE: "नाप",
  SELECT_COLOR: "रंग छान्नुहोस्",
  SELECT_SIZE: "नाप छान्नुहोस्",
  PLACE_ORDER: "अर्डर बुक गर्नुहोस्",
  CONTINUE: "जारी राख्नुहोस्",
  PROCEED_TO_PAYMENT: "भुक्तानीको लागि अघि बढ्नुहोस्",
  PAYMENT: "भुक्तानी",
  ADD_TO_CART:"कार्टमा हाल्नुहोस्",
  GO_TO_CART: "कार्टमा जानुहोस्",
  REVIEW_ORDER: "अर्डरको समीक्षा गर्नुहोस्",
  ADDRESS: "ठेगाना",
  ADD_ADDRESS: "ठेगाना थप्नुहोस्",
  EDIT_ADDRESS: "ठेगाना परिवर्तन गर्नुहोस्",
  TOTAL: "कूल",
  CONFIRM_ORDER: "अर्डर पुष्टि गर्नुहोस्",
  PRODUCT_COLOR:"रंग",
  YOU_MAY_ALSO_LIKE: "तपाईं पनि मन सक्छ",
  PRODUCTS_DECRIPTION: "उत्पाद विवरण",
  errorMobilePassword: "कृपया मोबाइल नम्बर र पासवर्ड प्रविष्ट गर्नुहोस्",
  errorMobile: "कृपया मान्य 10 अंकोंको मोबाइल नम्बर प्रविष्ट गर्नुहोस्",
  YOU_SAVED: "तपाईंले बचाए",
  BILLING_SUMMARY: "बिलिंग सारांश",
  TOTAL_ORIGINAL_PRICE: "कुल मूल कीमत",
  TOTAL_DISCOUNT: "कुल छूट",
  GST_AMOUNT: "GST राशि",
  NET_PAYABLE: "शुद्ध देय",
  WISHLIST: "इच्छा सूची",
  BUS_SERVICE: "बस सेवा",
  BOOKING_FOR_BUS: "{{bus}} को लागि बुकिङ",
  TICKET_BOOKING_STATUS: "तपाईंको टिकट बुकिंग",
  AGE: "उम्र",
  GENDER: "लिङ्ग",
  BUS_NO: "बस नम्बर",
  OPERATOR: "बस को नाम",
  TOTAL: "कुल",
  PASSENGERS: "यात्रुहरू",
  OPERATOR_PHONE: "हामीलाई सम्पर्क गर्नुहोस",
  RECHARGE: "रिचार्ज",
  RECHARGE_NOW: "अहिले रिचार्ज गर्नुहोस्",
  ENTER_MOBILE_KHALTI: "मोबाइल नम्बर / खल्ती आईडी प्रविष्ट गर्नुहोस्",
  ENTER_AMOUNT: "राशि प्रविष्ट गर्नुहोस् (20 - 25000)",
  MOBILE_RECHARGE_AND_TOP_UP: "मोबाइल रिचार्ज र टप अप",
  ENTER_MOBILE: "मोबाइल नम्बर प्रविष्ट गर्नुहोस्",
  SELECT_PACK: "रिचार्ज प्याक छान्नुहोस्",
  ADD_PASSENGER: "यात्रु थप्नुहोस्",
  BOOK_NOW: "बुक गर्नुहोस्",
  SOURCE: "स्रोत",
  DESTINATION: "गंतव्य",
  DATE: "तारीख",
  SELECT_SOURCE: "स्रोत चयन गर्नुहोस्",
  SELECT_DESTINATION: "गंतव्य चयन गर्नुहोस्",
  SELECT_DATE: "तारीख चयन गर्नुहोस्",
  SEARCH_BUSES: "बस खोज्नुहोस्",
  NO_BUSES_FOUND: "कुनै बस भेटिएन",
  PLEASE_SELECT_SOURCE_AND_DESTINATION: "कृपया स्रोत र गंतव्य चयन गर्नुहोस्",
  SOURCE_AND_DESTINATION_CANNOT_BE_SAME: "स्रोत र गंतव्य समान हुन सक्दैन",
  ERROR: "त्रुटि",
  SOMETHING_WENT_WRONG: "कुछ गलत हो गयो",
  TERMS_AND_CONDITIONS: "नियम र शर्तें",
  I_AGREE_TO_TERMS: "म नियमहरूसँग सहमत छु।",
  PHONE_NUMBER: "फोन नम्बर",
  NAME: "नाम",
  SELECT_GENDER: "लिङ्ग चयन गर्नुहोस्",
  NO_BOOKINGS: "कुनै बुकिङ भेटिएन",
  RECHARGE_HISTORY: "रिचार्ज इतिहास",
  RECHARGE_STATUS: "रिचार्ज स्थिति",
  STATUS: "स्थिति",
  EDIT_PROFILE: "प्रोफ़ाइल संपादित करें",
  WALLET_DETAILS: "वालेट विवरणहरू",
  MY_ORDERS: "मेरे ऑर्डर",
  ORDER_DETAILS: "ऑर्डर विवरण",
  ELECTRICITY_BILL: "बिजली बिल",
  BILLS_AND_RECHARGE: "बिल और रिचार्ज",
  TELANGANA_NEPALI_SABHA: "तेलंगाना नेपाली सभा",
  Either_in_ID_1_or_ID_2_Age_should_be_mentioned: "उमेर ID-1 वा ID-2 मा उल्लेख गर्नुपर्छ।",
  UPLOAD_ID_1_PROOF: "ID-1 प्रमाण अपलोड करें",
  UPLOAD_ID_2_PROOF: "ID-2 प्रमाण अपलोड करें",
  UPLOAD_NEPAL_ADDRESS_PROOF: "नेपाल ठेगानाको प्रमाण अपलोड गर्नुहोस्",
  UPLOAD_INDIA_PROOF: "भारत ठेगाना प्रमाण अपलोड गर्नुहोस्",
  CONTACT_NUMBER: "संपर्क नंबर",
  NEPAL_CONTACT_NUMBER: "नेपाल संपर्क नंबर",
  ENTER_NEPAL_CONTACT_NUMBER: "नेपाल सम्पर्क नम्बर प्रविष्ट गर्नुहोस्",
  ENTER_INDIA_CONTACT_NUMBER: "भारत सम्पर्क नम्बर प्रविष्ट गर्नुहोस्",
  INDIA_CONTACT_NUMBER: "भारत संपर्क नंबर",
  NEPAL_ADDRESS: "नेपाल पता",
  INDIA_ADDRESS: "भारत पता",
  NEPAL_PROOF_IMAGE: "नेपाल प्रमाण छवि",
  INDIA_PROOF_IMAGE: "भारत प्रमाण छवि",
  SUBMIT_APPLICATION: "आवेदन बुझाउनुहोस्",
  GENDER_MALE: "पुरुष",
  GENDER_FEMALE: "महिला",
  GENDER_OTHER: "अन्य",
  DOB: "जन्म मिति",
  NEPAL_CONTACT_NUMBER_LABEL: "नेपाल संपर्क नंबर",
  INDIA_CONTACT_NUMBER_LABEL: "भारत संपर्क नंबर",
  ID_1_NAME: "ID-1 नाम",
  ID_2_NAME: "ID-2 नाम",
  ENTER_NAME_FOR_ID_1: "आईडी-1 को नाम प्रविष्ट गर्नुहोस्",
  ENTER_NAME_FOR_ID_2: "आईडी-2 को नाम प्रविष्ट गर्नुहोस्",
  ID_1_OF_NEPAL: "नेपालको आईडी-1",
  ID_2_OF_NEPAL: "नेपालको आईडी-2",
  ENTER_ID_1_OF_NEPAL: "आफ्नो नेपाल आईडी-1 प्रविष्ट गर्नुहोस्",
  ENTER_ID_2_OF_NEPAL: "आफ्नो नेपाल आईडी-2 प्रविष्ट गर्नुहोस्।",
  ENTER_NEPAL_ADDRESS: "नेपाल ठेगाना प्रविष्ट गर्नुहोस्",
  ENTER_INDIA_ADDRESS: "भारतको ठेगाना प्रविष्ट गर्नुहोस्",
  DOB_PLACEHOLDER: "दिन/महिना/वर्ष",
  SUBMIT_APPLICATION: "आवेदन बुझाउनुहोस्",
  ENTER_ID_2_OF_NEPAL: "आफ्नो नेपाल आईडी-2 प्रविष्ट गर्नुहोस्",
  ENTER_ID_1_OF_NEPAL: "आफ्नो नेपाल आईडी-1 प्रविष्ट गर्नुहोस्",
  ENTER_INDIA_CONTACT_NUMBER: "भारत सम्पर्क नम्बर प्रविष्ट गर्नुहोस्",
  INFO: "जानकारी",
  PRAWASI_CARD_APPLICATION: "प्रवासी कार्ड आवेदन",
  MY_APPLICATIONS: "प्रवासी कार्ड आवेदन",
  CONTACT_US: "संपर्क करें",
  OUT_OF_STOCK: "स्टॉक समाप्त",
  ATTENTION: "ध्यान दिनुहोस्",
  TICKET_BOOKING_NETWORK_ERROR: "टिकट बुकिङ नेटवर्क त्रुटि",
  TICKET_BOOKING_NETWORK_ERROR_DETAIL: "यदि तपाईंको भुक्तानी सफल भएको छ भने, अस्थायी नेटवर्क समस्याका कारण तपाईंको बुकिङ अझै प्रक्रियामा हुन सक्छ।\n\nकृपया केही क्षणपछि आफ्नो बुकिङ इतिहास जाँच गर्नुहोस्। यदि तपाईंको बुकिङ अझै पनि देखिँदैन भने, कृपया आफ्नो भुक्तानी विवरण सहित हाम्रो सहायता टोलीलाई सम्पर्क गर्नुहोस्।",
  DELIVERY_CHARGES: "डेलिभरी शुल्क",
  PRODUCT_ADDED_TO_CART:
  "उत्पादन सफलतापूर्वक कार्टमा थपियो। अर्डर बुक गर्न 'कार्टमा जानुहोस्' थिच्नुहोस्। यदि तपाईं थप वस्तुहरू थप्न चाहनुहुन्छ भने \"खरीदारी जारी राख्नुहोस्\" थिच्नुहोस्।",
  CONTINUE_SHOPPING: "खरीदारी जारी राख्नुहोस्",
  GO_TO_CART: "कार्टमा जानुहोस्",
  SUCCESS: "सफलता",
  ERROR: "त्रुटि",
  OK: "ठीक छ",
  SUCCESSFULLY_ADDED: "सफलतापूर्वक थपियो",
  DELETE_ITEM: "वस्तु हटाउनुहोस्",
  DELETE_ITEM_CONFIRMATION: "के तपाईं साँच्चिकै यो वस्तु हटाउन चाहनुहुन्छ?",
  YES: "हो",
  NO: "होइन",
  CANCEL: "होइन",
  PLACE_ORDER: "अर्डर बुक गर्नुहोस्",
  PROCEED_TO_PAY: "भुक्तानीको लागि अघि बढ्नुहोस्",
  PAY_NOW: "अहिले भुक्तानी गर्नुहोस्",
  INTERNET_PROVIDERS: "इन्टरनेट प्रदायकहरू",
  MORE_IN: "अरु",
  CART_EMPTY: "तपाईंको कार्ट खाली छ",
};