const API = {
  HOME: '/user_home.php',
  LOGIN: '/login.php',
  REGISTER: '/user_register.php',
  PRODUCTS: '/products.php',
  ADD_TO_CART: '/add_to_cart.php',
  GET_CART: '/get_cart.php',
  UPDATE_CART: '/update_cart.php',
  ADD_PRODUCT: '/add-product.php',
  CATEGORIES: '/categories.php',
  CATEGORY_PRODUCTS: '/category_products.php',
  GET_ADRESS:'/get_addresses.php',
  ADD_ADRESS:'/add_addresses.php',
  UPDATE_ADDRESS:'/update_addresses.php',
  UPDATE_DEFAULT_ADDRESS:'/update_default_address.php',
  DELETE_ADDRESS: '/delete_address.php',
  GET_PRODUCT_DETAIL: '/get_product_detail.php',
  CHECK_WISHLIST: '/check_wishlist.php',
  ADD_WISHLIST: "/add_to_wishlist.php",
  REMOVE_WISHLIST: "remove_wishlist.php",
  APPLY_GST: "/getCartSummary.php",
  GET_WISHLIST: "/get_wishlist.php",
  SEARCH_BUSES: "/search_buses.php",
  BOOK_TICKET: "/book_ticket.php",
  GET_CITIES: "/get_cities.php",
  GET_USER_BOOKINGS: "get_user_bookings.php",
  RECHARGE: "/recharge.php",
  GET_DATA_PACKS: "/get_datapacks.php",
  BUY_DATA_PACK: "/buy_datapack.php",
  CREATE_PAYMENT: "/create_recharge_payment.php",
  CREATE_ORDER: "/create_recharge_order.php",
  CALCULATE_AMOUNT: "/calculate_amount.php",
  VERIFY_RECHARGE_PAYMENT: "/verify_recharge_payment.php",
  VERIFY_BUS_PAYMENT: "/verify_bus_payment.php",
  UPDATE_PAYMENT_STATUS: "/update_payment_status.php",
  REFUND_BOOKING: "/refund_booking.php",
  CREATE_BOOKING_ORDER: "/create_booking_order.php",
  CREATE_TEMP_BOOKING: "/create_temp_booking.php",
  BOOKING_INIT: "/booking_init.php",
  UPDATE_BOOKING_PAYMENT: "/update_booking_payment.php",
  CONFIRM_BOOKING: "/confirm_booking.php",
  REFUND_DIRECT: "/refund_direct.php", // 🔥 important // 🔥 important
  BUS_TICKET_TERMS_AND_CONDITIONS: "/bus_ticket_terms_and_conditions.php", // 🔥 important
  CANCEL_BOOKING: "/cancel_booking.php", // 🔥 important
  UPDATE_USER_PROFILE: "/update_user_profile.php", // 🔥 important
};

export default API;